"""Prescribed magnetic field, treated as an input to the solver.

The magnetic field is not learned by the network: it is supplied to the
pipeline the same way an inlet velocity or an outlet pressure would be. Each
function below returns a
[`FieldSample`][magnetofluidics_pinn.types.FieldSample] evaluated at given
coordinates, independent of the fluid-flow network.
"""

from __future__ import annotations

import torch

from magnetofluidics_pinn.types import FieldSample


def uniform_field(
    coordinates: torch.Tensor, magnitude: float, orientation: tuple[float, float]
) -> FieldSample:
    """Evaluate a spatially and temporally constant magnetic field.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `magnitude`: Field magnitude, in `tesla`.
    - `orientation`: Unit vector giving the field direction.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with a
      constant field vector repeated at every coordinate.

    Raises:
    - `ValueError`: If `orientation` is not (approximately) a unit vector.
    """
    raise NotImplementedError("Implementation scheduled for Step 2.")


def gradient_field(
    coordinates: torch.Tensor, magnitude: float, gradient: tuple[float, float]
) -> FieldSample:
    """Evaluate a linearly varying (non-uniform) magnetic field.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `magnitude`: Reference field magnitude at the domain origin, in `tesla`.
    - `gradient`: Spatial gradient of the field magnitude along each axis, in
      `tesla-per-meter`.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
    """
    raise NotImplementedError("Implementation scheduled for a later roadmap phase.")


def biot_savart_field(
    coordinates: torch.Tensor,
    source_currents: torch.Tensor,
    source_positions: torch.Tensor,
) -> FieldSample:
    """Evaluate a magnetic field generated by known current sources.

    Computes the field from the Biot-Savart law given a set of discretized
    current-carrying source segments, independently of the flow solver.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `source_currents`: Tensor of shape `(n_sources,)` with the current
      carried by each source segment, in `ampere`.
    - `source_positions`: Tensor of shape `(n_sources, n_dims)` with the
      position of each source segment.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
    """
    raise NotImplementedError("Implementation scheduled for a later roadmap phase.")
