"""Prescribed magnetic field, treated as an input to the solver.

The network does not learn the magnetic field: it is supplied to the
pipeline the same way an inlet velocity or outlet pressure would be. Each
function below returns a
[`FieldSample`][magnetofluidics_pinn.types.FieldSample] evaluated at given
coordinates, independent of the fluid-flow network.
"""

from __future__ import annotations

import torch

from magnetofluidics_pinn.types import FieldSample

# Numerical tolerance used to check that `orientation` is (approximately) a
# unit vector; loose enough to tolerate float32 rounding, tight enough to
# catch a genuinely mis-specified direction.
_UNIT_NORM_TOLERANCE = 1.0e-6


def uniform_field(
        coordinates: torch.Tensor, magnitude: float, orientation: tuple[float, float]
) -> FieldSample:
    """Evaluate a spatially and temporally constant magnetic field.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `magnitude`: Field magnitude, in `tesla`.
    - `orientation`: Unit vector giving the field direction.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with a
      constant field vector repeated at every coordinate.

    Raises:
    - `ValueError`: If `orientation` is not (approximately) a unit vector, if
      `coordinates` is not a 2-D tensor, or if `orientation`'s length does
      not match `coordinates`'s number of dimensions.
    """
    if coordinates.ndim != 2:
        raise ValueError(
            f"coordinates must have shape (n_points, n_dims); got {tuple(coordinates.shape)}."
        )
    
    orientation_tensor = torch.as_tensor(
        orientation, dtype=coordinates.dtype, device=coordinates.device
    )
    if orientation_tensor.shape[0] != coordinates.shape[1]:
        raise ValueError(
            "orientation must have as many components as coordinates has "
            f"dimensions; got {orientation_tensor.shape[0]} vs {coordinates.shape[1]}."
        )
    
    orientation_norm = torch.linalg.norm(orientation_tensor)
    if not torch.isclose(
            orientation_norm, torch.ones_like(orientation_norm), atol=_UNIT_NORM_TOLERANCE
    ):
        raise ValueError(
            f"orientation must be a unit vector; got a norm of {orientation_norm.item():.6g}."
        )
    
    # The field does not depend on `coordinates` (it is uniform in
    # space); it is broadcast to match the sample count purely so that
    # `FieldSample.field` has the shape callers expect.
    field_vector = magnitude * orientation_tensor
    field = field_vector.unsqueeze(0).expand(coordinates.shape[0], -1).clone()
    return FieldSample(coordinates=coordinates, field=field)


def gradient_field(
        coordinates: torch.Tensor, magnitude: float, gradient: tuple[float, float]
) -> FieldSample:
    """Evaluate a linearly varying (non-uniform) magnetic field.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `magnitude`: Reference field magnitude at the domain origin, in `tesla`.
    - `gradient`: Spatial gradient of the field magnitude along each axis, in
      `tesla-per-meter`.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
    """
    raise NotImplementedError("Implementation scheduled for a later roadmap phase.")


def biot_savart_field(
        coordinates: torch.Tensor,
        source_currents: torch.Tensor,
        source_positions: torch.Tensor,
) -> FieldSample:
    """Evaluate a magnetic field generated by known current sources.

    Computes the field from the Biot-Savart law given a set of discretized
    current-carrying source segments, independently of the flow solver.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `source_currents`: Tensor of shape `(n_sources,)` with the current
      carried by each source segment, in `ampere`.
    - `source_positions`: Tensor of shape `(n_sources, n_dims)` with the
      position of each source segment.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
    """
    raise NotImplementedError("Implementation scheduled for a later roadmap phase.")
