"""Prescribed magnetic field, treated as an input to the solver.

The network does not learn the magnetic field: it is supplied to the
pipeline the same way an inlet velocity or outlet pressure would be. Each
function below returns a
[`FieldSample`][magnetofluidics_pinn.types.FieldSample] evaluated at given
coordinates, independent of the fluid-flow network.
"""

from __future__ import annotations

import math  # NEW
import torch

from magnetofluidics_pinn.types import MagneticFieldSample

# Numerical tolerance used to check that `orientation` is (approximately) a
# unit vector; loose enough to tolerate float32 rounding, tight enough to
# catch a genuinely mis-specified direction.
_UNIT_NORM_TOLERANCE = 1.0e-6


def uniform_field(
        coordinates: torch.Tensor, magnitude: float, orientation: tuple[float, float]
) -> MagneticFieldSample:
    """Evaluate a spatially and temporally constant magnetic field.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `magnitude`: Field magnitude, in `tesla`.
    - `orientation`: Unit vector giving the field direction.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with a
      constant field vector repeated at every coordinate.

    Raises:
    - `ValueError`: If `orientation` is not (approximately) a unit vector, if
      `coordinates` is not a 2-D tensor, or if `orientation`'s length does
      not match `coordinates`'s number of dimensions.
    """
    if coordinates.ndim != 2:
        raise ValueError(
            f"coordinates must have shape (n_points, n_dims); got {tuple(coordinates.shape)}."
        )
    
    orientation_tensor = torch.as_tensor(
        orientation, dtype=coordinates.dtype, device=coordinates.device
    )
    if orientation_tensor.shape[0] != coordinates.shape[1]:
        raise ValueError(
            "orientation must have as many components as coordinates has "
            f"dimensions; got {orientation_tensor.shape[0]} vs {coordinates.shape[1]}."
        )
    
    orientation_norm = torch.linalg.norm(orientation_tensor)
    if not torch.isclose(
            orientation_norm, torch.ones_like(orientation_norm), atol=_UNIT_NORM_TOLERANCE
    ):
        raise ValueError(
            f"orientation must be a unit vector; got a norm of {orientation_norm.item():.6g}."
        )
    
    # The field does not depend on `coordinates` (it is uniform in
    # space); it is broadcast to match the sample count purely so that
    # `FieldSample.field` has the shape callers expect.
    field_vector = magnitude * orientation_tensor
    field = field_vector.unsqueeze(0).expand(coordinates.shape[0], -1).clone()
    return MagneticFieldSample(coordinates=coordinates, field=field)


def gradient_field(
        coordinates: torch.Tensor, magnitude: float, gradient: tuple[float, float]
) -> MagneticFieldSample:
    r"""Evaluate the linear, Maxwell-consistent axisymmetric field with an axial gradient.

    $$ B_r = g_r\,r,\qquad B_z = B_0 + g_z\,z,\qquad g_r = -\tfrac12 g_z. $$

    In a current-free region $\div\mathbf B = 2g_r + g_z = 0$ and
    $\curl\mathbf B = \mathbf 0$. An arbitrary pair $(g_r, g_z)$ would violate Gauss's law and
    make $\nabla(\mathbf m\cdot\mathbf B) \ne (\mathbf m\cdot\nabla)\mathbf B$, so it is rejected
    [@abbott2020magnetic]. Output is in **SI** (tesla); inputs are in meter.

    Args:
    - `coordinates`: Tensor `(n_points, 2)` of `(r, z)` points, in meter.
    - `magnitude`: Axial field $B_0$ at the origin, in tesla.
    - `gradient`: Pair `(g_r, g_z)` in (T), with `g_r = -g_z / 2`.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
   
    Raises:
    - `ValueError`: If `coordinates` is not `(n_points, 2)`, a value is not finite, or the gradient
      violates $\div\mathbf B = 0$.
    """
    if coordinates.ndim != 2 or coordinates.shape[1] != 2:
        raise ValueError(f"coordinates must have shape (n_points, 2); got {tuple(coordinates.shape)}.")
    g_r, g_z = gradient
    if not all(math.isfinite(value) for value in (magnitude, g_r, g_z)):
        raise ValueError("magnitude and gradient components must be finite.")
    if not math.isclose(g_r, -0.5 * g_z, rel_tol=1.0e-9, abs_tol=1.0e-12 * max(1.0, abs(g_z))):
        raise ValueError(f"gradient must satisfy g_r = -g_z / 2 (div B = 0); got {gradient!r}.")
    b_r = g_r * coordinates[:, 0:1]
    b_z = magnitude + g_z * coordinates[:, 1:2]
    return MagneticFieldSample(coordinates=coordinates, field=torch.cat([b_r, b_z], dim=1))


def biot_savart_field(
        coordinates: torch.Tensor,
        source_currents: torch.Tensor,
        source_positions: torch.Tensor,
) -> MagneticFieldSample:
    """Evaluate a magnetic field generated by known current sources.

    Computes the field from the Biot-Savart law given a set of discretized
    current-carrying source segments, independently of the flow solver.

    Args:
    - `coordinates`: Tensor of shape `(n_points, n_dims)` where the field is
      evaluated.
    - `source_currents`: Tensor of shape `(n_sources,)` with the current
      carried by each source segment, in `ampere`.
    - `source_positions`: Tensor of shape `(n_sources, n_dims)` with the
      position of each source segment.

    Returns:
    - A [`FieldSample`][magnetofluidics_pinn.types.FieldSample] with the field
      vector evaluated at each coordinate.
    """
    raise NotImplementedError("Implementation scheduled for a later roadmap phase.")
